// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: rpc_demo.proto

package rpc_demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcDemoClient is the client API for RpcDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcDemoClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type rpcDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcDemoClient(cc grpc.ClientConnInterface) RpcDemoClient {
	return &rpcDemoClient{cc}
}

func (c *rpcDemoClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpc_demo.Rpc_demo/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcDemoServer is the server API for RpcDemo service.
// All implementations must embed UnimplementedRpcDemoServer
// for forward compatibility
type RpcDemoServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRpcDemoServer()
}

// UnimplementedRpcDemoServer must be embedded to have forward compatible implementations.
type UnimplementedRpcDemoServer struct {
}

func (UnimplementedRpcDemoServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRpcDemoServer) mustEmbedUnimplementedRpcDemoServer() {}

// UnsafeRpcDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcDemoServer will
// result in compilation errors.
type UnsafeRpcDemoServer interface {
	mustEmbedUnimplementedRpcDemoServer()
}

func RegisterRpcDemoServer(s grpc.ServiceRegistrar, srv RpcDemoServer) {
	s.RegisterService(&RpcDemo_ServiceDesc, srv)
}

func _RpcDemo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDemoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_demo.Rpc_demo/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDemoServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcDemo_ServiceDesc is the grpc.ServiceDesc for RpcDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_demo.Rpc_demo",
	HandlerType: (*RpcDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RpcDemo_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_demo.proto",
}
