// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
	Age  string `path:"age,options=20|30"`
}

type Response struct {
	Message string `json:"message"`
}
